In [ ]:
import os
import json
import pandas as pd
import psycopg2

### CONVERT TO DATAFRAME

In [3]:
#aggre_insurance
path1= "S:/DS PROJECT/phonepe/pulse/data/aggregated/insurance/country/india/state/"

agg_insur_list= os.listdir(path1)

columns1= {"States":[], "Years":[], "Quarter":[], "Insurance_type":[], "Insurance_count":[],"Insurance_amount":[] }

for state in agg_insur_list:
    cur_states =path1+state+"/"
    agg_year_list = os.listdir(cur_states)
    
    for year in agg_year_list:
        cur_years = cur_states+year+"/"
        agg_file_list = os.listdir(cur_years)

        for file in agg_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            A = json.load(data)

            for i in A["data"]["transactionData"]:
                name = i["name"]
                count = i["paymentInstruments"][0]["count"]
                amount = i["paymentInstruments"][0]["amount"]
                columns1["Insurance_type"].append(name)
                columns1["Insurance_count"].append(count)
                columns1["Insurance_amount"].append(amount)
                columns1["States"].append(state)
                columns1["Years"].append(year)
                columns1["Quarter"].append(int(file.strip(".json")))


aggre_insurance = pd.DataFrame(columns1)

aggre_insurance["States"] = aggre_insurance["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
aggre_insurance["States"] = aggre_insurance["States"].str.replace("-"," ")
aggre_insurance["States"] = aggre_insurance["States"].str.title()
aggre_insurance['States'] = aggre_insurance['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [4]:
A

{'success': True,
 'code': 'SUCCESS',
 'data': {'from': 1727740800000,
  'to': 1735344000000,
  'transactionData': [{'name': 'Insurance',
    'paymentInstruments': [{'type': 'TOTAL',
      'count': 91719,
      'amount': 120602777.0}]}]},
 'responseTimestamp': 1739974635383}

In [5]:
aggre_insurance

,States,Years,Quarter,Insurance_type,Insurance_count,Insurance_amount
0,Andaman & Nicobar,2020,2,Insurance,6,1360.0
1,Andaman & Nicobar,2020,3,Insurance,41,15380.0
2,Andaman & Nicobar,2020,4,Insurance,124,157975.0
3,Andaman & Nicobar,2021,1,Insurance,225,244266.0
4,Andaman & Nicobar,2021,2,Insurance,137,181504.0
...,...,...,...,...,...,...
677,West Bengal,2023,4,Insurance,72712,100365562.0
678,West Bengal,2024,1,Insurance,79576,104987909.0
679,West Bengal,2024,2,Insurance,67048,89476633.0
680,West Bengal,2024,3,Insurance,77158,107451766.0
681,West Bengal,2024,4,Insurance,91719,120602777.0

In [6]:
#aggre_transaction
path2 = "S:/DS PROJECT/phonepe/pulse/data/aggregated/transaction/country/india/state/"
         
agg_tran_list = os.listdir(path2)

columns2 ={"States":[], "Years":[], "Quarter":[], "Transaction_type":[], "Transaction_count":[],"Transaction_amount":[] }

for state in agg_tran_list:
    cur_states =path2+state+"/"
    agg_year_list = os.listdir(cur_states)
    
    for year in agg_year_list:
        cur_years = cur_states+year+"/"
        agg_file_list = os.listdir(cur_years)

        for file in agg_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            B = json.load(data)

            for i in B["data"]["transactionData"]:
                name = i["name"]
                count = i["paymentInstruments"][0]["count"]
                amount = i["paymentInstruments"][0]["amount"]
                columns2["Transaction_type"].append(name)
                columns2["Transaction_count"].append(count)
                columns2["Transaction_amount"].append(amount)
                columns2["States"].append(state)
                columns2["Years"].append(year)
                columns2["Quarter"].append(int(file.strip(".json")))

aggre_transaction = pd.DataFrame(columns2)

aggre_transaction["States"] = aggre_transaction["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
aggre_transaction["States"] = aggre_transaction["States"].str.replace("-"," ")
aggre_transaction["States"] = aggre_transaction["States"].str.title()
aggre_transaction['States'] = aggre_transaction['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [7]:
B

{'success': True,
 'code': 'SUCCESS',
 'data': {'from': 1727740800000,
  'to': 1735344000000,
  'transactionData': [{'name': 'Merchant payments',
    'paymentInstruments': [{'type': 'TOTAL',
      'count': 655100809,
      'amount': 389286175909.0}]},
   {'name': 'Peer-to-peer payments',
    'paymentInstruments': [{'type': 'TOTAL',
      'count': 493217788,
      'amount': 1361927136312.0}]},
   {'name': 'Recharge & bill payments',
    'paymentInstruments': [{'type': 'TOTAL',
      'count': 76043195,
      'amount': 57534056540.0}]},
   {'name': 'Financial Services',
    'paymentInstruments': [{'type': 'TOTAL',
      'count': 2352084,
      'amount': 847296537.0}]},
   {'name': 'Others',
    'paymentInstruments': [{'type': 'TOTAL',
      'count': 421806,
      'amount': 505364108.0}]}]},
 'responseTimestamp': 1739974491270}

In [8]:
aggre_transaction

,States,Years,Quarter,Transaction_type,Transaction_count,Transaction_amount
0,Andaman & Nicobar,2018,1,Recharge & bill payments,4200,1.845307e+06
1,Andaman & Nicobar,2018,1,Peer-to-peer payments,1871,1.213866e+07
2,Andaman & Nicobar,2018,1,Merchant payments,298,4.525072e+05
3,Andaman & Nicobar,2018,1,Financial Services,33,1.060142e+04
4,Andaman & Nicobar,2018,1,Others,256,1.846899e+05
...,...,...,...,...,...,...
5029,West Bengal,2024,4,Merchant payments,655100809,3.892862e+11
5030,West Bengal,2024,4,Peer-to-peer payments,493217788,1.361927e+12
5031,West Bengal,2024,4,Recharge & bill payments,76043195,5.753406e+10
5032,West Bengal,2024,4,Financial Services,2352084,8.472965e+08
5033,West Bengal,2024,4,Others,421806,5.053641e+08

In [9]:
#aggre_user
path3 = "S:/DS PROJECT/phonepe/pulse/data/aggregated/user/country/india/state/"
         
agg_user_list = os.listdir(path3)

columns3 = {"States":[], "Years":[], "Quarter":[], "Brands":[],"Transaction_count":[], "Percentage":[]}

for state in agg_user_list:
    cur_states = path3+state+"/"
    agg_year_list = os.listdir(cur_states)
    
    for year in agg_year_list:
        cur_years = cur_states+year+"/"
        agg_file_list = os.listdir(cur_years)
        
        for file in agg_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            C = json.load(data)

            try:

                for i in C["data"]["usersByDevice"]:
                    brand = i["brand"]
                    count = i["count"]
                    percentage = i["percentage"]
                    columns3["Brands"].append(brand)
                    columns3["Transaction_count"].append(count)
                    columns3["Percentage"].append(percentage)
                    columns3["States"].append(state)
                    columns3["Years"].append(year)
                    columns3["Quarter"].append(int(file.strip(".json")))
            
            except:
                pass

aggre_user = pd.DataFrame(columns3)

aggre_user["States"] = aggre_user["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
aggre_user["States"] = aggre_user["States"].str.replace("-"," ")
aggre_user["States"] = aggre_user["States"].str.title()
aggre_user['States'] = aggre_user['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [10]:
C

{'success': True,
 'code': 'SUCCESS',
 'data': {'aggregated': {'registeredUsers': 34750181, 'appOpens': 1994940763},
  'usersByDevice': None},
 'responseTimestamp': 1739974566918}

In [11]:
aggre_user

                 States Years  Quarter   Brands  Transaction_count  Percentage
0     Andaman & Nicobar  2018        1   Xiaomi               1665    0.247033
1     Andaman & Nicobar  2018        1  Samsung               1445    0.214392
2     Andaman & Nicobar  2018        1     Vivo                982    0.145697
3     Andaman & Nicobar  2018        1     Oppo                501    0.074332
4     Andaman & Nicobar  2018        1  OnePlus                332    0.049258
...                 ...   ...      ...      ...                ...         ...
6727        West Bengal  2022        1   Lenovo             330017    0.015056
6728        West Bengal  2022        1  Infinix             284678    0.012987
6729        West Bengal  2022        1     Asus             280347    0.012790
6730        West Bengal  2022        1    Apple             277752    0.012671
6731        West Bengal  2022        1   Others            2196334    0.100199

[6732 rows x 6 columns]

In [13]:
#map_insurance
path4= "S:/DS PROJECT/phonepe/pulse/data/map/insurance/hover/country/india/state/"

map_insur_list= os.listdir(path4)

columns4= {"States":[], "Years":[], "Quarter":[], "Districts":[], "Transaction_count":[],"Transaction_amount":[] }

for state in map_insur_list:
    cur_states =path4+state+"/"
    agg_year_list = os.listdir(cur_states)
    
    for year in agg_year_list:
        cur_years = cur_states+year+"/"
        agg_file_list = os.listdir(cur_years)

        for file in agg_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            D = json.load(data)

            for i in D["data"]["hoverDataList"]:
                name = i["name"]
                count = i["metric"][0]["count"]
                amount = i["metric"][0]["amount"]
                columns4["Districts"].append(name)
                columns4["Transaction_count"].append(count)
                columns4["Transaction_amount"].append(amount)
                columns4["States"].append(state)
                columns4["Years"].append(year)
                columns4["Quarter"].append(int(file.strip(".json")))


map_insurance = pd.DataFrame(columns4)

map_insurance["States"] = map_insurance["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
map_insurance["States"] = map_insurance["States"].str.replace("-"," ")
map_insurance["States"] = map_insurance["States"].str.title()
map_insurance['States'] = map_insurance['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [14]:
D

{'success': True,
 'code': 'SUCCESS',
 'data': {'hoverDataList': [{'name': 'south twenty four parganas district',
    'metric': [{'type': 'TOTAL', 'count': 6659, 'amount': 7720038.0}]},
   {'name': 'purba bardhaman district',
    'metric': [{'type': 'TOTAL', 'count': 3595, 'amount': 4482879.0}]},
   {'name': 'uttar dinajpur district',
    'metric': [{'type': 'TOTAL', 'count': 1730, 'amount': 2115117.0}]},
   {'name': 'kalimpong district',
    'metric': [{'type': 'TOTAL', 'count': 137, 'amount': 298205.0}]},
   {'name': 'murshidabad district',
    'metric': [{'type': 'TOTAL', 'count': 3214, 'amount': 3386355.0}]},
   {'name': 'paschim medinipur district',
    'metric': [{'type': 'TOTAL', 'count': 4155, 'amount': 5405054.0}]},
   {'name': 'dakshin dinajpur district',
    'metric': [{'type': 'TOTAL', 'count': 818, 'amount': 948223.0}]},
   {'name': 'jalpaiguri district',
    'metric': [{'type': 'TOTAL', 'count': 1622, 'amount': 2307554.0}]},
   {'name': 'purulia district',
    'metric': [{'type': 'TOTAL', 'count': 1337, 'amount': 1889679.0}]},
   {'name': 'north twenty four parganas district',
    'metric': [{'type': 'TOTAL', 'count': 16080, 'amount': 22630772.0}]},
   {'name': 'bankura district',
    'metric': [{'type': 'TOTAL', 'count': 1882, 'amount': 2245707.0}]},
   {'name': 'jhargram district',
    'metric': [{'type': 'TOTAL', 'count': 537, 'amount': 800920.0}]},
   {'name': 'darjeeling district',
    'metric': [{'type': 'TOTAL', 'count': 3478, 'amount': 5191531.0}]},
   {'name': 'cooch behar district',
    'metric': [{'type': 'TOTAL', 'count': 1709, 'amount': 2090821.0}]},
   {'name': 'malda district',
    'metric': [{'type': 'TOTAL', 'count': 4042, 'amount': 4902098.0}]},
   {'name': 'howrah district',
    'metric': [{'type': 'TOTAL', 'count': 6763, 'amount': 8567180.0}]},
   {'name': 'hooghly district',
    'metric': [{'type': 'TOTAL', 'count': 5089, 'amount': 6642595.0}]},
   {'name': 'kolkata district',
    'metric': [{'type': 'TOTAL', 'count': 13720, 'amount': 18465410.0}]},
   {'name': 'alipurduar district',
    'metric': [{'type': 'TOTAL', 'count': 1023, 'amount': 1613143.0}]},
   {'name': 'paschim bardhaman district',
    'metric': [{'type': 'TOTAL', 'count': 4945, 'amount': 7005851.0}]},
   {'name': 'nadia district',
    'metric': [{'type': 'TOTAL', 'count': 3807, 'amount': 5031294.0}]},
   {'name': 'birbhum district',
    'metric': [{'type': 'TOTAL', 'count': 1818, 'amount': 2423290.0}]},
   {'name': 'purba medinipur district',
    'metric': [{'type': 'TOTAL', 'count': 3559, 'amount': 4439061.0}]}]},
 'responseTimestamp': 1739974635574}

In [16]:
map_insurance

,States,Years,Quarter,Districts,Transaction_count,Transaction_amount
0,Andaman & Nicobar,2020,2,south andaman district,3,795.0
1,Andaman & Nicobar,2020,2,nicobars district,3,565.0
2,Andaman & Nicobar,2020,3,north and middle andaman district,1,281.0
3,Andaman & Nicobar,2020,3,south andaman district,35,13651.0
4,Andaman & Nicobar,2020,3,nicobars district,5,1448.0
...,...,...,...,...,...,...
13871,West Bengal,2024,4,alipurduar district,1023,1613143.0
13872,West Bengal,2024,4,paschim bardhaman district,4945,7005851.0
13873,West Bengal,2024,4,nadia district,3807,5031294.0
13874,West Bengal,2024,4,birbhum district,1818,2423290.0
13875,West Bengal,2024,4,purba medinipur district,3559,4439061.0

In [15]:
#map_transaction
path5 = "S:/DS PROJECT/phonepe/pulse/data/map/transaction/hover/country/india/state/"
map_tran_list = os.listdir(path5)

columns5 = {"States":[], "Years":[], "Quarter":[],"District":[], "Transaction_count":[],"Transaction_amount":[]}

for state in map_tran_list:
    cur_states = path5+state+"/"
    map_year_list = os.listdir(cur_states)
    
    for year in map_year_list:
        cur_years = cur_states+year+"/"
        map_file_list = os.listdir(cur_years)
        
        for file in map_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            E = json.load(data)

            for i in E['data']["hoverDataList"]:
                name = i["name"]
                count = i["metric"][0]["count"]
                amount = i["metric"][0]["amount"]
                columns5["District"].append(name)
                columns5["Transaction_count"].append(count)
                columns5["Transaction_amount"].append(amount)
                columns5["States"].append(state)
                columns5["Years"].append(year)
                columns5["Quarter"].append(int(file.strip(".json")))

map_transaction = pd.DataFrame(columns5)

map_transaction["States"] = map_transaction["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
map_transaction["States"] = map_transaction["States"].str.replace("-"," ")
map_transaction["States"] = map_transaction["States"].str.title()
map_transaction['States'] = map_transaction['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [17]:
E

{'success': True,
 'code': 'SUCCESS',
 'data': {'hoverDataList': [{'name': 'south twenty four parganas district',
    'metric': [{'type': 'TOTAL',
      'count': 76936211,
      'amount': 118552623594.0}]},
   {'name': 'purba bardhaman district',
    'metric': [{'type': 'TOTAL', 'count': 43690070, 'amount': 70602865584.0}]},
   {'name': 'uttar dinajpur district',
    'metric': [{'type': 'TOTAL', 'count': 37198721, 'amount': 61950132057.0}]},
   {'name': 'kalimpong district',
    'metric': [{'type': 'TOTAL', 'count': 1847818, 'amount': 2646924444.0}]},
   {'name': 'murshidabad district',
    'metric': [{'type': 'TOTAL',
      'count': 88522023,
      'amount': 156002264967.0}]},
   {'name': 'paschim medinipur district',
    'metric': [{'type': 'TOTAL', 'count': 58238212, 'amount': 84317739854.0}]},
   {'name': 'dakshin dinajpur district',
    'metric': [{'type': 'TOTAL', 'count': 13106067, 'amount': 21452200306.0}]},
   {'name': 'jalpaiguri district',
    'metric': [{'type': 'TOTAL', 'count': 20696406, 'amount': 27260366555.0}]},
   {'name': 'purulia district',
    'metric': [{'type': 'TOTAL', 'count': 24755604, 'amount': 26562481159.0}]},
   {'name': 'north twenty four parganas district',
    'metric': [{'type': 'TOTAL',
      'count': 199005333,
      'amount': 256651022725.0}]},
   {'name': 'bankura district',
    'metric': [{'type': 'TOTAL', 'count': 27187898, 'amount': 38703687103.0}]},
   {'name': 'jhargram district',
    'metric': [{'type': 'TOTAL', 'count': 8887423, 'amount': 11463658026.0}]},
   {'name': 'darjeeling district',
    'metric': [{'type': 'TOTAL', 'count': 27795067, 'amount': 40187454877.0}]},
   {'name': 'cooch behar district',
    'metric': [{'type': 'TOTAL', 'count': 33080526, 'amount': 42135373824.0}]},
   {'name': 'malda district',
    'metric': [{'type': 'TOTAL',
      'count': 63424613,
      'amount': 102421242316.0}]},
   {'name': 'howrah district',
    'metric': [{'type': 'TOTAL',
      'count': 67496284,
      'amount': 102576375745.0}]},
   {'name': 'hooghly district',
    'metric': [{'type': 'TOTAL', 'count': 59676576, 'amount': 90713828065.0}]},
   {'name': 'kolkata district',
    'metric': [{'type': 'TOTAL',
      'count': 133085069,
      'amount': 185223784274.0}]},
   {'name': 'alipurduar district',
    'metric': [{'type': 'TOTAL', 'count': 15875637, 'amount': 20992506730.0}]},
   {'name': 'paschim bardhaman district',
    'metric': [{'type': 'TOTAL', 'count': 56616799, 'amount': 69687350676.0}]},
   {'name': 'nadia district',
    'metric': [{'type': 'TOTAL',
      'count': 65274337,
      'amount': 107932013030.0}]},
   {'name': 'birbhum district',
    'metric': [{'type': 'TOTAL', 'count': 36905213, 'amount': 57787007226.0}]},
   {'name': 'purba medinipur district',
    'metric': [{'type': 'TOTAL',
      'count': 67833775,
      'amount': 114277126269.0}]}]},
 'responseTimestamp': 1739974491469}

In [18]:
map_transaction

,States,Years,Quarter,District,Transaction_count,Transaction_amount
0,Andaman & Nicobar,2018,1,north and middle andaman district,442,9.316631e+05
1,Andaman & Nicobar,2018,1,south andaman district,5688,1.256025e+07
2,Andaman & Nicobar,2018,1,nicobars district,528,1.139849e+06
3,Andaman & Nicobar,2018,2,north and middle andaman district,825,1.317863e+06
4,Andaman & Nicobar,2018,2,south andaman district,9395,2.394824e+07
...,...,...,...,...,...,...
20599,West Bengal,2024,4,alipurduar district,15875637,2.099251e+10
20600,West Bengal,2024,4,paschim bardhaman district,56616799,6.968735e+10
20601,West Bengal,2024,4,nadia district,65274337,1.079320e+11
20602,West Bengal,2024,4,birbhum district,36905213,5.778701e+10
20603,West Bengal,2024,4,purba medinipur district,67833775,1.142771e+11

In [19]:
#map_user
path6 = "S:/DS PROJECT/phonepe/pulse/data/map/user/hover/country/india/state/"
map_user_list = os.listdir(path6)

columns6 = {"States":[], "Years":[], "Quarter":[], "Districts":[], "RegisteredUser":[], "AppOpens":[]}

for state in map_user_list:
    cur_states = path6+state+"/"
    map_year_list = os.listdir(cur_states)
    
    for year in map_year_list:
        cur_years = cur_states+year+"/"
        map_file_list = os.listdir(cur_years)
        
        for file in map_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            F = json.load(data)

            for i in F["data"]["hoverData"].items():
                district = i[0]
                registereduser = i[1]["registeredUsers"]
                appopens = i[1]["appOpens"]
                columns6["Districts"].append(district)
                columns6["RegisteredUser"].append(registereduser)
                columns6["AppOpens"].append(appopens)
                columns6["States"].append(state)
                columns6["Years"].append(year)
                columns6["Quarter"].append(int(file.strip(".json")))

map_user = pd.DataFrame(columns6)

map_user["States"] = map_user["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
map_user["States"] = map_user["States"].str.replace("-"," ")
map_user["States"] = map_user["States"].str.title()
map_user['States'] = map_user['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [20]:
F

{'success': True,
 'code': 'SUCCESS',
 'data': {'hoverData': {'south twenty four parganas district': {'registeredUsers': 2525913,
    'appOpens': 148514597},
   'purba bardhaman district': {'registeredUsers': 1435548,
    'appOpens': 84180749},
   'uttar dinajpur district': {'registeredUsers': 922938,
    'appOpens': 66212953},
   'kalimpong district': {'registeredUsers': 78277, 'appOpens': 4244012},
   'murshidabad district': {'registeredUsers': 2463675, 'appOpens': 165497019},
   'paschim medinipur district': {'registeredUsers': 1522845,
    'appOpens': 80731143},
   'dakshin dinajpur district': {'registeredUsers': 489732,
    'appOpens': 30374022},
   'jalpaiguri district': {'registeredUsers': 647266, 'appOpens': 42531734},
   'purulia district': {'registeredUsers': 809355, 'appOpens': 56448658},
   'north twenty four parganas district': {'registeredUsers': 5085095,
    'appOpens': 234840305},
   'bankura district': {'registeredUsers': 1017304, 'appOpens': 49393224},
   'jhargram district': {'registeredUsers': 282208, 'appOpens': 14361554},
   'darjeeling district': {'registeredUsers': 881187, 'appOpens': 56941907},
   'cooch behar district': {'registeredUsers': 932485, 'appOpens': 53702834},
   'malda district': {'registeredUsers': 1444985, 'appOpens': 122226269},
   'howrah district': {'registeredUsers': 2140752, 'appOpens': 116704834},
   'hooghly district': {'registeredUsers': 1957356, 'appOpens': 96383119},
   'kolkata district': {'registeredUsers': 3476288, 'appOpens': 178709399},
   'alipurduar district': {'registeredUsers': 475688, 'appOpens': 31842355},
   'paschim bardhaman district': {'registeredUsers': 1468252,
    'appOpens': 80543469},
   'nadia district': {'registeredUsers': 1861738, 'appOpens': 98740305},
   'birbhum district': {'registeredUsers': 1114220, 'appOpens': 73465525},
   'purba medinipur district': {'registeredUsers': 1717074,
    'appOpens': 108350777}}},
 'responseTimestamp': 1739974567116}

In [21]:
map_user

,States,Years,Quarter,Districts,RegisteredUser,AppOpens
0,Andaman & Nicobar,2018,1,north and middle andaman district,632,0
1,Andaman & Nicobar,2018,1,south andaman district,5846,0
2,Andaman & Nicobar,2018,1,nicobars district,262,0
3,Andaman & Nicobar,2018,2,north and middle andaman district,911,0
4,Andaman & Nicobar,2018,2,south andaman district,8143,0
...,...,...,...,...,...,...
20603,West Bengal,2024,4,alipurduar district,475688,31842355
20604,West Bengal,2024,4,paschim bardhaman district,1468252,80543469
20605,West Bengal,2024,4,nadia district,1861738,98740305
20606,West Bengal,2024,4,birbhum district,1114220,73465525
20607,West Bengal,2024,4,purba medinipur district,1717074,108350777

In [22]:
#top_insurance

path7 = "S:/DS PROJECT/phonepe/pulse/data/top/insurance/country/india/state/"

top_insur_list = os.listdir(path7)

columns7 = {"States":[], "Years":[], "Quarter":[], "Pincodes":[], "Transaction_count":[], "Transaction_amount":[]}

for state in top_insur_list:
    cur_states = path7+state+"/"
    top_year_list = os.listdir(cur_states)

    for year in top_year_list:
        cur_years = cur_states+year+"/"
        top_file_list = os.listdir(cur_years)

        for file in top_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            G = json.load(data)

            for i in G["data"]["pincodes"]:
                entityName = i["entityName"]
                count = i["metric"]["count"]
                amount = i["metric"]["amount"]
                columns7["Pincodes"].append(entityName)
                columns7["Transaction_count"].append(count)
                columns7["Transaction_amount"].append(amount)
                columns7["States"].append(state)
                columns7["Years"].append(year)
                columns7["Quarter"].append(int(file.strip(".json")))

top_insur = pd.DataFrame(columns7)

top_insur["States"] = top_insur["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
top_insur["States"] = top_insur["States"].str.replace("-"," ")
top_insur["States"] = top_insur["States"].str.title()
top_insur['States'] = top_insur['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [23]:
G

{'success': True,
 'code': 'SUCCESS',
 'data': {'states': None,
  'districts': [{'entityName': 'north twenty four parganas',
    'metric': {'type': 'TOTAL', 'count': 16080, 'amount': 22630772.0}},
   {'entityName': 'kolkata',
    'metric': {'type': 'TOTAL', 'count': 13720, 'amount': 18465410.0}},
   {'entityName': 'howrah',
    'metric': {'type': 'TOTAL', 'count': 6763, 'amount': 8567180.0}},
   {'entityName': 'south twenty four parganas',
    'metric': {'type': 'TOTAL', 'count': 6659, 'amount': 7720038.0}},
   {'entityName': 'hooghly',
    'metric': {'type': 'TOTAL', 'count': 5089, 'amount': 6642595.0}},
   {'entityName': 'paschim bardhaman',
    'metric': {'type': 'TOTAL', 'count': 4945, 'amount': 7005851.0}},
   {'entityName': 'paschim medinipur',
    'metric': {'type': 'TOTAL', 'count': 4155, 'amount': 5405054.0}},
   {'entityName': 'malda',
    'metric': {'type': 'TOTAL', 'count': 4042, 'amount': 4902098.0}},
   {'entityName': 'nadia',
    'metric': {'type': 'TOTAL', 'count': 3807, 'amount': 5031294.0}},
   {'entityName': 'purba bardhaman',
    'metric': {'type': 'TOTAL', 'count': 3595, 'amount': 4482879.0}}],
  'pincodes': [{'entityName': '721301',
    'metric': {'type': 'TOTAL', 'count': 1131, 'amount': 1510819.0}},
   {'entityName': '734001',
    'metric': {'type': 'TOTAL', 'count': 890, 'amount': 1231954.0}},
   {'entityName': '700135',
    'metric': {'type': 'TOTAL', 'count': 759, 'amount': 1361002.0}},
   {'entityName': '732101',
    'metric': {'type': 'TOTAL', 'count': 739, 'amount': 912493.0}},
   {'entityName': '700059',
    'metric': {'type': 'TOTAL', 'count': 732, 'amount': 1082245.0}},
   {'entityName': '711101',
    'metric': {'type': 'TOTAL', 'count': 713, 'amount': 750354.0}},
   {'entityName': '700091',
    'metric': {'type': 'TOTAL', 'count': 642, 'amount': 969634.0}},
   {'entityName': '700150',
    'metric': {'type': 'TOTAL', 'count': 627, 'amount': 761501.0}},
   {'entityName': '700039',
    'metric': {'type': 'TOTAL', 'count': 619, 'amount': 787836.0}},
   {'entityName': '700156',
    'metric': {'type': 'TOTAL', 'count': 574, 'amount': 888613.0}}]},
 'responseTimestamp': 1739974635778}

In [24]:
top_insur

,States,Years,Quarter,Pincodes,Transaction_count,Transaction_amount
0,Andaman & Nicobar,2020,2,744301,3,565.0
1,Andaman & Nicobar,2020,2,744104,2,513.0
2,Andaman & Nicobar,2020,2,744101,1,282.0
3,Andaman & Nicobar,2020,3,744112,9,3432.0
4,Andaman & Nicobar,2020,3,744105,7,3948.0
...,...,...,...,...,...,...
6663,West Bengal,2024,4,711101,713,750354.0
6664,West Bengal,2024,4,700091,642,969634.0
6665,West Bengal,2024,4,700150,627,761501.0
6666,West Bengal,2024,4,700039,619,787836.0
6667,West Bengal,2024,4,700156,574,888613.0

In [25]:
#top_transaction
path8 = "S:/DS PROJECT/phonepe/pulse/data/top/transaction/country/india/state/"
top_tran_list = os.listdir(path8)

columns8 = {"States":[], "Years":[], "Quarter":[], "Pincodes":[], "Transaction_count":[], "Transaction_amount":[]}

for state in top_tran_list:
    cur_states = path8+state+"/"
    top_year_list = os.listdir(cur_states)
    
    for year in top_year_list:
        cur_years = cur_states+year+"/"
        top_file_list = os.listdir(cur_years)
        
        for file in top_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            H = json.load(data)

            for i in H["data"]["pincodes"]:
                entityName = i["entityName"]
                count = i["metric"]["count"]
                amount = i["metric"]["amount"]
                columns8["Pincodes"].append(entityName)
                columns8["Transaction_count"].append(count)
                columns8["Transaction_amount"].append(amount)
                columns8["States"].append(state)
                columns8["Years"].append(year)
                columns8["Quarter"].append(int(file.strip(".json")))

top_transaction = pd.DataFrame(columns8)

top_transaction["States"] = top_transaction["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
top_transaction["States"] = top_transaction["States"].str.replace("-"," ")
top_transaction["States"] = top_transaction["States"].str.title()
top_transaction['States'] = top_transaction['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [26]:
H

{'success': True,
 'code': 'SUCCESS',
 'data': {'states': None,
  'districts': [{'entityName': 'north twenty four parganas',
    'metric': {'type': 'TOTAL', 'count': 199005333, 'amount': 256651022725.0}},
   {'entityName': 'kolkata',
    'metric': {'type': 'TOTAL', 'count': 133085069, 'amount': 185223784274.0}},
   {'entityName': 'murshidabad',
    'metric': {'type': 'TOTAL', 'count': 88522023, 'amount': 156002264967.0}},
   {'entityName': 'south twenty four parganas',
    'metric': {'type': 'TOTAL', 'count': 76936211, 'amount': 118552623594.0}},
   {'entityName': 'purba medinipur',
    'metric': {'type': 'TOTAL', 'count': 67833775, 'amount': 114277126269.0}},
   {'entityName': 'howrah',
    'metric': {'type': 'TOTAL', 'count': 67496284, 'amount': 102576375745.0}},
   {'entityName': 'nadia',
    'metric': {'type': 'TOTAL', 'count': 65274337, 'amount': 107932013030.0}},
   {'entityName': 'malda',
    'metric': {'type': 'TOTAL', 'count': 63424613, 'amount': 102421242316.0}},
   {'entityName': 'hooghly',
    'metric': {'type': 'TOTAL', 'count': 59676576, 'amount': 90713828065.0}},
   {'entityName': 'paschim medinipur',
    'metric': {'type': 'TOTAL', 'count': 58238212, 'amount': 84317739854.0}}],
  'pincodes': [{'entityName': '721301',
    'metric': {'type': 'TOTAL', 'count': 13780795, 'amount': 15889322487.0}},
   {'entityName': '700135',
    'metric': {'type': 'TOTAL', 'count': 11229299, 'amount': 12643541299.0}},
   {'entityName': '700156',
    'metric': {'type': 'TOTAL', 'count': 9407190, 'amount': 7954583067.0}},
   {'entityName': '700091',
    'metric': {'type': 'TOTAL', 'count': 8280505, 'amount': 6655130955.0}},
   {'entityName': '700161',
    'metric': {'type': 'TOTAL', 'count': 7542766, 'amount': 7001428872.0}},
   {'entityName': '711101',
    'metric': {'type': 'TOTAL', 'count': 6753348, 'amount': 10494826024.0}},
   {'entityName': '700059',
    'metric': {'type': 'TOTAL', 'count': 6662715, 'amount': 8009476497.0}},
   {'entityName': '700039',
    'metric': {'type': 'TOTAL', 'count': 6575693, 'amount': 9018748395.0}},
   {'entityName': '734001',
    'metric': {'type': 'TOTAL', 'count': 6432082, 'amount': 8996529284.0}},
   {'entityName': '733134',
    'metric': {'type': 'TOTAL', 'count': 6313560, 'amount': 10502594688.0}}]},
 'responseTimestamp': 1739974491708}

In [27]:
top_transaction

,States,Years,Quarter,Pincodes,Transaction_count,Transaction_amount
0,Andaman & Nicobar,2018,1,744101,1622,2.769298e+06
1,Andaman & Nicobar,2018,1,744103,1223,2.238042e+06
2,Andaman & Nicobar,2018,1,744102,969,3.519060e+06
3,Andaman & Nicobar,2018,1,744105,685,1.298561e+06
4,Andaman & Nicobar,2018,1,744104,340,1.039715e+06
...,...,...,...,...,...,...
9994,West Bengal,2024,4,711101,6753348,1.049483e+10
9995,West Bengal,2024,4,700059,6662715,8.009476e+09
9996,West Bengal,2024,4,700039,6575693,9.018748e+09
9997,West Bengal,2024,4,734001,6432082,8.996529e+09
9998,West Bengal,2024,4,733134,6313560,1.050259e+10

In [28]:
#top_user
path9 = "S:/DS PROJECT/phonepe/pulse/data/top/user/country/india/state/"
top_user_list = os.listdir(path9)

columns9 = {"States":[], "Years":[], "Quarter":[], "Pincodes":[], "RegisteredUser":[]}

for state in top_user_list:
    cur_states = path9+state+"/"
    top_year_list = os.listdir(cur_states)

    for year in top_year_list:
        cur_years = cur_states+year+"/"
        top_file_list = os.listdir(cur_years)

        for file in top_file_list:
            cur_files = cur_years+file
            data = open(cur_files,"r")
            I = json.load(data)

            for i in I["data"]["pincodes"]:
                name = i["name"]
                registeredusers = i["registeredUsers"]
                columns9["Pincodes"].append(name)
                columns9["RegisteredUser"].append(registereduser)
                columns9["States"].append(state)
                columns9["Years"].append(year)
                columns9["Quarter"].append(int(file.strip(".json")))

top_user = pd.DataFrame(columns9)

top_user["States"] = top_user["States"].str.replace("andaman-&-nicobar-islands","Andaman & Nicobar")
top_user["States"] = top_user["States"].str.replace("-"," ")
top_user["States"] = top_user["States"].str.title()
top_user['States'] = top_user['States'].str.replace("Dadra & Nagar Haveli & Daman & Diu", "Dadra and Nagar Haveli and Daman and Diu")

In [29]:
I

{'success': True,
 'code': 'SUCCESS',
 'data': {'states': None,
  'districts': [{'name': 'north twenty four parganas',
    'registeredUsers': 5085095},
   {'name': 'kolkata', 'registeredUsers': 3476288},
   {'name': 'south twenty four parganas', 'registeredUsers': 2525913},
   {'name': 'murshidabad', 'registeredUsers': 2463675},
   {'name': 'howrah', 'registeredUsers': 2140752},
   {'name': 'hooghly', 'registeredUsers': 1957356},
   {'name': 'nadia', 'registeredUsers': 1861738},
   {'name': 'purba medinipur', 'registeredUsers': 1717074},
   {'name': 'paschim medinipur', 'registeredUsers': 1522845},
   {'name': 'paschim bardhaman', 'registeredUsers': 1468252}],
  'pincodes': [{'name': '721301', 'registeredUsers': 260807},
   {'name': '700135', 'registeredUsers': 205916},
   {'name': '734001', 'registeredUsers': 201449},
   {'name': '711101', 'registeredUsers': 178662},
   {'name': '700039', 'registeredUsers': 172027},
   {'name': '733134', 'registeredUsers': 169596},
   {'name': '700059', 'registeredUsers': 169448},
   {'name': '711302', 'registeredUsers': 146034},
   {'name': '700150', 'registeredUsers': 142151},
   {'name': '711106', 'registeredUsers': 142077}]},
 'responseTimestamp': 1739974567331}

In [30]:
top_user

                 States Years  Quarter Pincodes  RegisteredUser
0     Andaman & Nicobar  2018        1   744103         1717074
1     Andaman & Nicobar  2018        1   744101         1717074
2     Andaman & Nicobar  2018        1   744105         1717074
3     Andaman & Nicobar  2018        1   744102         1717074
4     Andaman & Nicobar  2018        1   744104         1717074
...                 ...   ...      ...      ...             ...
9995        West Bengal  2024        4   733134         1717074
9996        West Bengal  2024        4   700059         1717074
9997        West Bengal  2024        4   711302         1717074
9998        West Bengal  2024        4   700150         1717074
9999        West Bengal  2024        4   711106         1717074

[10000 rows x 5 columns]

### DATA TRANSFER TO DATABASE

In [29]:
#Table Creation
#pgsql connection

mydb=psycopg2.connect(host="localhost",
                      user="postgres",
                      port="5432",
                      password="venkat",
                      database="phonepe_data")
cursor=mydb.cursor()


#aggregated insurance table
create_query1= '''CREATE TABLE if not exists aggregated_insurance (States varchar(50),
                                                                      Years int,
                                                                      Quarter int,
                                                                      Insurance_type varchar(50),
                                                                      Insurance_count bigint,
                                                                      Insurance_amount bigint
                                                                      )'''
cursor.execute(create_query1)
mydb.commit()

for index,row in aggre_insurance.iterrows():
    insert_query1 = '''INSERT INTO aggregated_insurance (States, Years, Quarter, Insurance_type, Insurance_count, Insurance_amount)
                                                        values(%s,%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Insurance_type"],
              row["Insurance_count"],
              row["Insurance_amount"]
              )
    cursor.execute(insert_query1,values)
    mydb.commit()

#aggregated transaction table
create_query2 = '''CREATE TABLE if not exists aggregated_transaction (States varchar(50),
                                                                      Years int,
                                                                      Quarter int,
                                                                      Transaction_type varchar(50),
                                                                      Transaction_count bigint,
                                                                      Transaction_amount bigint
                                                                      )'''
cursor.execute(create_query2)
mydb.commit()

for index,row in aggre_transaction.iterrows():
    insert_query2 = '''INSERT INTO aggregated_transaction (States, Years, Quarter, Transaction_type, Transaction_count, Transaction_amount)
                                                        values(%s,%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Transaction_type"],
              row["Transaction_count"],
              row["Transaction_amount"]
              )
    cursor.execute(insert_query2,values)
    mydb.commit()

#aggregated user table
create_query3 = '''CREATE TABLE if not exists aggregated_user (States varchar(50),
                                                                Years int,
                                                                Quarter int,
                                                                Brands varchar(50),
                                                                Transaction_count bigint,
                                                                Percentage float)'''
cursor.execute(create_query3)
mydb.commit()

for index,row in aggre_user.iterrows():
    insert_query3 = '''INSERT INTO aggregated_user (States, Years, Quarter, Brands, Transaction_count, Percentage)
                                                    values(%s,%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Brands"],
              row["Transaction_count"],
              row["Percentage"])
    cursor.execute(insert_query3,values)
    mydb.commit()

#map_insurance_table
create_query4 = '''CREATE TABLE if not exists map_insurance (States varchar(50),
                                                                Years int,
                                                                Quarter int,
                                                                District varchar(50),
                                                                Transaction_count bigint,
                                                                Transaction_amount float)'''
cursor.execute(create_query4)
mydb.commit()

for index,row in map_insurance.iterrows():
            insert_query4 = '''
                INSERT INTO map_insurance (States, Years, Quarter, District, Transaction_count, Transaction_amount)
                VALUES (%s, %s, %s, %s, %s, %s)

            '''
            values = (
                row['States'],
                row['Years'],
                row['Quarter'],
                row['Districts'],
                row['Transaction_count'],
                row['Transaction_amount']
            )
            cursor.execute(insert_query4,values)
            mydb.commit() 

#map_transaction_table
create_query5 = '''CREATE TABLE if not exists map_transaction (States varchar(50),
                                                                Years int,
                                                                Quarter int,
                                                                District varchar(50),
                                                                Transaction_count bigint,
                                                                Transaction_amount float)'''
cursor.execute(create_query5)
mydb.commit()

for index,row in map_transaction.iterrows():
            insert_query5 = '''
                INSERT INTO map_Transaction (States, Years, Quarter, District, Transaction_count, Transaction_amount)
                VALUES (%s, %s, %s, %s, %s, %s)

            '''
            values = (
                row['States'],
                row['Years'],
                row['Quarter'],
                row['District'],
                row['Transaction_count'],
                row['Transaction_amount']
            )
            cursor.execute(insert_query5,values)
            mydb.commit() 


#map_user_table
create_query6 = '''CREATE TABLE if not exists map_user (States varchar(50),
                                                        Years int,
                                                        Quarter int,
                                                        Districts varchar(50),
                                                        RegisteredUser bigint,
                                                        AppOpens bigint)'''
cursor.execute(create_query6)
mydb.commit()

for index,row in map_user.iterrows():
    insert_query6 = '''INSERT INTO map_user (States, Years, Quarter, Districts, RegisteredUser, AppOpens)
                        values(%s,%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Districts"],
              row["RegisteredUser"],
              row["AppOpens"])
    cursor.execute(insert_query6,values)
    mydb.commit()

#top_insurance_table
create_query7 = '''CREATE TABLE if not exists top_insurance (States varchar(50),
                                                                Years int,
                                                                Quarter int,
                                                                Pincodes int,
                                                                Transaction_count bigint,
                                                                Transaction_amount bigint)'''
cursor.execute(create_query7)
mydb.commit()

for index,row in top_insur.iterrows():
    insert_query7 = '''INSERT INTO top_insurance (States, Years, Quarter, Pincodes, Transaction_count, Transaction_amount)
                                                    values(%s,%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Pincodes"],
              row["Transaction_count"],
              row["Transaction_amount"])
    cursor.execute(insert_query7,values)
    mydb.commit()

#top_transaction_table
create_query8 = '''CREATE TABLE if not exists top_transaction (States varchar(50),
                                                                Years int,
                                                                Quarter int,
                                                                pincodes int,
                                                                Transaction_count bigint,
                                                                Transaction_amount bigint)'''
cursor.execute(create_query8)
mydb.commit()

for index,row in top_transaction.iterrows():
    insert_query8 = '''INSERT INTO top_transaction (States, Years, Quarter, Pincodes, Transaction_count, Transaction_amount)
                                                    values(%s,%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Pincodes"],
              row["Transaction_count"],
              row["Transaction_amount"])
    cursor.execute(insert_query8,values)
    mydb.commit()

#top_user_table
create_query9 = '''CREATE TABLE if not exists top_user (States varchar(50),
                                                        Years int,
                                                        Quarter int,
                                                        Pincodes int,
                                                        RegisteredUser bigint
                                                        )'''
cursor.execute(create_query9)
mydb.commit()

for index,row in top_user.iterrows():
    insert_query9 = '''INSERT INTO top_user (States, Years, Quarter, Pincodes, RegisteredUser)
                                            values(%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Pincodes"],
              row["RegisteredUser"])
    cursor.execute(insert_query9,values)
    mydb.commit()